name: Publish Docker image

on:
  push:
    branches: [master]
    tags-ignore: ['*']

jobs:
  push:
    strategy:
      matrix:
        version: [0.11.4, 1.0.3]

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the container registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: tetafro
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.0.0
        with:
          context: ${{ matrix.version }}
          push: true
          tags: ghcr.io/tetafro/caddy:v${{ matrix.version }}
